// Ported verbatim from TRAINING_CHECKLISTS in src/threatpad.py.
export type ChecklistSection = [name: string, items: string[]];
export type ChecklistMap = Record<string, ChecklistSection[]>;

export const TRAINING_CHECKLISTS: ChecklistMap = {
  Phishing: [
    ["TRIAGE", [
      "Identify the reporting user and collection method (email forward, ticket, verbal)",
      "Obtain the original email headers (not a screenshot -- raw headers)",
      "Confirm whether the email was clicked, credentials entered, or attachments opened",
      "Check how many users received the same email (targeted vs. bulk campaign)",
    ]],
    ["EMAIL ANALYSIS", [
      "Extract and defang sender address, reply-to, and return-path fields",
      "Check SPF, DKIM, and DMARC alignment in headers",
      "Extract all URLs from body and headers -- defang before logging",
      "Extract any attachment names, types, and hashes (MD5/SHA256)",
      "Check sending infrastructure: IP reputation via AbuseIPDB, domain age/WHOIS",
    ]],
    ["IOC ENRICHMENT", [
      "Submit URLs to VirusTotal / URLScan.io",
      "Submit attachment hashes to VirusTotal",
      "Check sender domain against threat intel feeds",
      "Search SIEM for same sender, subject, or URL across all users",
    ]],
    ["CONTAINMENT", [
      "Block sender address and sending IP at email gateway",
      "Block identified malicious URLs at proxy/firewall",
      "Quarantine or delete the email from all affected mailboxes",
      "If credentials were entered: initiate password reset immediately",
      "If attachment was opened: isolate the endpoint for forensic review",
    ]],
    ["ESCALATION CHECK", [
      "Were credentials compromised? → Escalate to L2 / Identity team",
      "Was malware executed? → Escalate to L2 / IR team, isolate host",
      "Is this a targeted spearphishing campaign? → Escalate to L2",
      "Multiple users affected across departments? → Escalate to L2",
    ]],
    ["CLOSURE", [
      "Document full timeline: reported → triaged → contained → resolved",
      "Record all IOCs extracted in the ticket",
      "Confirm no further mailboxes are affected",
      "User awareness: advise reporting user of outcome",
      "Lessons learned: was anything missed in filtering/detection?",
    ]],
  ],
  Malware: [
    ["TRIAGE", [
      "Identify the affected host(s): hostname, IP, OS, owner, department",
      "Determine detection source: AV alert, EDR, SIEM rule, user report",
      "Confirm malware family if known (ransomware, trojan, infostealer, etc.)",
      "Establish initial infection vector if possible (email, web, USB, lateral)",
    ]],
    ["EVIDENCE COLLECTION", [
      "Capture the file path, name, and hash (MD5 + SHA256) of the malicious file",
      "Pull process tree: parent process, child processes, command-line arguments",
      "Capture network connections made by the process at time of execution",
      "Pull relevant event logs: 4688 (process creation), 7045 (service install), Sysmon if available",
      "Note any persistence mechanisms: registry run keys, scheduled tasks, services",
    ]],
    ["IOC ENRICHMENT", [
      "Submit file hash to VirusTotal -- note detection ratio and family",
      "Check C2 IPs/domains against AbuseIPDB and threat intel",
      "Search SIEM for same hash or C2 across all endpoints",
      "Check for lateral movement: same user or admin credentials used elsewhere?",
    ]],
    ["CONTAINMENT", [
      "Isolate the affected endpoint from the network immediately",
      "Block identified C2 IPs and domains at firewall/proxy",
      "Disable or reset any accounts that ran the malicious process",
      "Revoke any tokens or sessions associated with compromised accounts",
      "Notify endpoint owner and their manager",
    ]],
    ["ESCALATION CHECK", [
      "Is this ransomware or wiper malware? → Escalate to L2 / IR immediately",
      "Evidence of lateral movement or credential harvesting? → Escalate to L2",
      "Multiple hosts affected? → Escalate to L2",
      "Persistence mechanism found? → Escalate to L2 for full remediation",
    ]],
    ["CLOSURE", [
      "Confirm endpoint has been reimaged or fully remediated",
      "Verify C2 blocks are in place and verified at network layer",
      "Confirm no other hosts are affected via SIEM sweep",
      "Document full attack chain in ticket with timeline",
      "Update detection rules if this bypassed existing signatures",
    ]],
  ],
  "Brute Force": [
    ["TRIAGE", [
      "Identify the targeted account(s) and service (VPN, RDP, OWA, SSH, etc.)",
      "Determine source IP(s) -- single IP, distributed, or credential stuffing pattern",
      "Check whether any authentication attempts succeeded",
      "Identify timeframe: first failed attempt to detection time",
    ]],
    ["INVESTIGATION", [
      "Pull authentication logs for the targeted account(s) -- last 7 days minimum",
      "Check for successful logins from unusual IPs, locations, or times",
      "Identify if the attack is targeted (single account) or widespread (multiple accounts)",
      "Check source IPs against AbuseIPDB -- known scanner or botnet?",
      "Review MFA logs: was MFA prompted? Was it bypassed or fatigue-attacked?",
    ]],
    ["IOC ENRICHMENT", [
      "Submit attacking IPs to AbuseIPDB",
      "Check if usernames match a known breach list (if tooling permits)",
      "Search SIEM for same source IPs across other services",
      "Check for impossible travel or session anomalies on any successful logins",
    ]],
    ["CONTAINMENT", [
      "Block source IPs at firewall/WAF/VPN gateway",
      "Lock or temporarily disable targeted account(s) if at risk",
      "Force password reset on any accounts with successful logins during attack window",
      "Revoke active sessions for affected accounts",
      "Enforce MFA if not already in place on targeted service",
    ]],
    ["ESCALATION CHECK", [
      "Any successful logins during the attack window? → Escalate to L2",
      "MFA bypassed or push fatigue attack confirmed? → Escalate to L2",
      "Targeting privileged or admin accounts? → Escalate to L2",
      "Attack pattern suggests coordinated campaign? → Escalate to L2",
    ]],
    ["CLOSURE", [
      "Confirm source IPs are blocked and no further attempts are occurring",
      "Confirm affected accounts are secured and sessions revoked",
      "Document attack timeline, source IPs, and targeted accounts",
      "Recommend account lockout policy review if thresholds allowed excessive attempts",
      "Note whether geo-blocking or conditional access rules should be tightened",
    ]],
  ],
  "Unauthorised Access": [
    ["TRIAGE", [
      "Identify which system, application, or data was accessed without authorisation",
      "Identify the account used -- internal, external, service account, or unknown",
      "Determine whether access was accidental, insider threat, or external compromise",
      "Establish the timeframe of the unauthorised access",
    ]],
    ["INVESTIGATION", [
      "Pull access logs for the affected system for the full suspected window",
      "Identify what data or resources were accessed, modified, or exfiltrated",
      "Review authentication logs: how was access obtained? VPN, direct, web, API?",
      "Check if the account was compromised (concurrent sessions, unusual location/time)",
      "Review privilege logs: was privilege escalation used to gain access?",
    ]],
    ["IOC ENRICHMENT", [
      "Check source IPs used against AbuseIPDB and geo lookup",
      "Search SIEM for the account's activity across all systems in the window",
      "Check for data staging, compression, or large file transfers",
      "Review DLP alerts if available for the timeframe",
    ]],
    ["CONTAINMENT", [
      "Disable the compromised account immediately",
      "Revoke all active sessions and tokens",
      "Block source IPs if external access was used",
      "Preserve all relevant logs before any rotation or deletion occurs",
      "Notify system/data owner of the unauthorised access",
    ]],
    ["ESCALATION CHECK", [
      "Sensitive, personal, or regulated data was accessed? → Escalate to L2 / DPO",
      "Insider threat indicators? → Escalate to L2 / HR / Legal",
      "Evidence of data exfiltration? → Escalate to L2 / IR immediately",
      "Privileged or admin account involved? → Escalate to L2",
    ]],
    ["CLOSURE", [
      "Confirm account is secured and access revoked",
      "Document exactly what was accessed and whether data was exfiltrated",
      "Assess whether a data breach notification is required (GDPR / regulatory)",
      "Review access controls -- was least privilege in place?",
      "Document timeline and all evidence in the ticket",
    ]],
  ],
  "Data Exfiltration": [
    ["TRIAGE", [
      "Identify the source of the alert: DLP, CASB, SIEM rule, user report, or network anomaly",
      "Identify the user or system responsible for the transfer",
      "Determine what data was transferred and the approximate volume",
      "Identify the destination: external email, USB, cloud storage, remote IP, etc.",
    ]],
    ["INVESTIGATION", [
      "Pull full transfer logs for the suspected window -- confirm volume and destination",
      "Classify the data: is it sensitive, personal, regulated, or classified?",
      "Review if the transfer method was authorised (business justification?)",
      "Check for staging behaviour: large file creation, compression, or renaming before transfer",
      "Review user's recent activity for other anomalies or policy violations",
      "Check if other users or systems have transferred data to the same destination",
    ]],
    ["IOC ENRICHMENT", [
      "Look up destination IPs/domains -- known file sharing, personal cloud, or C2?",
      "Check if destination is a known data broker or exfiltration service",
      "Search SIEM for other transfers to the same destination across all users",
      "Cross-reference with any concurrent phishing or malware incidents",
    ]],
    ["CONTAINMENT", [
      "Block the destination IP/domain at proxy/firewall",
      "Suspend or disable the account responsible if compromise or malicious intent is suspected",
      "Revoke sessions and tokens for the account",
      "Preserve all logs and evidence immediately -- do not allow log rotation",
      "Notify data/system owner and escalate to management if sensitive data is involved",
    ]],
    ["ESCALATION CHECK", [
      "Personal data (PII) confirmed exfiltrated? → Escalate to DPO -- potential GDPR breach",
      "Volume or sensitivity suggests intentional exfiltration? → Escalate to L2 / Legal / HR",
      "Malware or external attacker involved? → Escalate to L2 / IR immediately",
      "Regulated data (financial, healthcare)? → Escalate and initiate breach protocol",
    ]],
    ["CLOSURE", [
      "Confirm exfiltration vector is blocked",
      "Document exactly what data was exfiltrated, volume, destination, and timeline",
      "Confirm whether regulatory breach notification is required and to whom",
      "Recommend DLP rule tuning if detection was delayed",
      "Document the full incident timeline and all evidence in the ticket",
    ]],
  ],
  Ransomware: [
    ["TRIAGE -- ACT FAST", [
      "Confirm ransomware activity: encrypted files, ransom note, or EDR/AV alert",
      "Identify affected host(s): hostname, IP, OS, owner, department",
      "IMMEDIATELY notify L2 / IR lead -- ransomware is a P1 incident",
      "Do NOT reboot or power off hosts without L2 instruction -- this may destroy evidence",
    ]],
    ["IMMEDIATE CONTAINMENT", [
      "Isolate ALL affected hosts from the network immediately (network isolation, not shutdown)",
      "Identify and isolate any hosts showing similar IOCs proactively",
      "Disable the affected user account(s) immediately",
      "Notify IT infrastructure team to suspend backups temporarily (to prevent backup encryption)",
      "Check whether backups are already affected -- this is critical",
    ]],
    ["EVIDENCE COLLECTION", [
      "Capture ransom note contents and file paths",
      "Identify the ransomware family if possible (via EDR, hash lookup, or note format)",
      "Pull process tree and execution chain from EDR",
      "Capture network connections made by the ransomware process",
      "Check for lateral movement: which other systems did the infected host connect to?",
      "Identify initial infection vector: phishing email, RDP exposure, vulnerable service?",
    ]],
    ["IOC ENRICHMENT", [
      "Submit ransomware hash to VirusTotal -- identify family and known C2",
      "Check C2 IPs/domains against threat intel -- block immediately",
      "Search SIEM for same hash, C2, or execution pattern across all endpoints",
      "Check ID Ransomware (https://id-ransomware.malwarehunterteam.com) for family identification",
    ]],
    ["ESCALATION -- MANDATORY", [
      "Escalate to L2 / IR team immediately if not already done",
      "Notify CISO / management -- this is a major incident",
      "Engage legal if data exfiltration is suspected (double extortion)",
      "If regulated data is involved, initiate breach notification protocol",
      "Do not engage with threat actor or pay ransom without legal/management authorisation",
    ]],
    ["CLOSURE (POST-IR)", [
      "Confirm all affected systems are reimaged -- not just cleaned",
      "Verify backups are clean and restoration has been tested",
      "Confirm all IOCs are blocked at network and endpoint level",
      "Document full attack chain, timeline, and impact in the ticket",
      "Conduct post-incident review -- how did ransomware execute and persist?",
    ]],
  ],
  "Other / Unknown": [
    ["TRIAGE", [
      "Describe the alert or suspicious activity clearly in the ticket",
      "Identify affected users, systems, or services",
      "Determine detection source: automated alert, user report, or proactive hunt",
      "Assess urgency: is there active, ongoing malicious activity?",
    ]],
    ["INVESTIGATION", [
      "Collect relevant logs for the suspected timeframe",
      "Identify any IOCs: IPs, domains, hashes, email addresses, file paths",
      "Search SIEM for related activity across other users or systems",
      "Determine whether this matches a known TTP or attack pattern",
    ]],
    ["IOC ENRICHMENT", [
      "Check any identified IPs against AbuseIPDB",
      "Submit any hashes to VirusTotal",
      "Check domains for age, reputation, and passive DNS history",
      "Search for the activity pattern in threat intel sources",
    ]],
    ["CONTAINMENT", [
      "Block any confirmed malicious IPs or domains",
      "Isolate any affected endpoints if active compromise is suspected",
      "Disable accounts if credential compromise is suspected",
      "Preserve all logs and evidence",
    ]],
    ["ESCALATION CHECK", [
      "Unable to determine scope or root cause? → Escalate to L2",
      "Active, ongoing threat activity? → Escalate to L2 immediately",
      "Sensitive data potentially involved? → Escalate to L2",
      "Incident type matches a P1 category (ransomware, mass data loss)? → Escalate immediately",
    ]],
    ["CLOSURE", [
      "Document all investigation steps taken and findings",
      "Record all IOCs in the ticket",
      "Confirm containment actions are in place",
      "Note any unresolved questions or recommended follow-up actions",
      "Update incident type classification if root cause was identified",
    ]],
  ],
  "Rare and Potentially High-Risk Office Operations": [
    ["TRIAGE", [
      "Identify the user account and specific Office operation flagged (e.g. eDiscovery export, mailbox delegation, audit log clearing, admin role assignment)",
      "Determine whether this is a first-time or rare operation for this user",
      "Confirm whether the operation was performed interactively or via an app/service principal",
      "Check whether the operation was performed from a known trusted IP, location, and device",
    ]],
    ["INVESTIGATION", [
      "Pull the full Unified Audit Log (UAL) entry — note ClientIP, UserAgent, and ResultStatus",
      "Review the user's UAL activity for the past 7 days for other anomalous operations",
      "Check sign-in logs: unusual location, IP, device, or time",
      "Verify whether MFA was satisfied for the session that performed the operation",
      "Identify what the operation acted on: which mailbox, site, or tenant setting was affected",
      "If mailbox delegation or forwarding was set: identify the recipient and verify legitimacy",
      "If eDiscovery was run: identify the scope and whether results were exported",
      "If audit logging was modified or cleared: treat as high severity and escalate immediately",
      "Check for concurrent alerts: impossible travel, suspicious sign-in, MFA bypass",
    ]],
    ["IOC ENRICHMENT", [
      "Check the source IP against AbuseIPDB and threat intel feeds",
      "Check the UserAgent string for anomalies (automation tools, unusual browsers)",
      "If a service principal performed the operation: review its permissions and recent activity",
      "Search SIEM for same operation performed by other accounts in the same window",
    ]],
    ["CONTAINMENT", [
      "If unauthorised: disable the account and revoke all active sessions and tokens",
      "Reverse the operation where possible (remove delegation, remove forwarding rule, restore audit settings)",
      "If data was exported via eDiscovery: notify the DPO and begin data breach assessment",
      "If admin role was assigned: remove the role immediately and audit what the new admin did",
      "Block the source IP at the network/conditional access layer if external and suspicious",
    ]],
    ["ESCALATION CHECK", [
      "Audit log cleared or disabled? → Escalate to L2 immediately",
      "eDiscovery export completed with sensitive data? → Escalate to L2 / DPO",
      "Admin role granted to unexpected account? → Escalate to L2 / CISO",
      "Account confirmed compromised? → Escalate to L2 / Identity team",
      "Multiple rare operations in same session? → Escalate to L2",
    ]],
    ["CLOSURE", [
      "Confirm the unauthorised operation has been reversed or remediated",
      "Confirm account is secured: password reset, MFA re-enrolled, sessions revoked",
      "Document the operation, resource affected, source IP, and timeline",
      "If data exposure occurred: complete formal data breach assessment",
    ]],
  ],
  "Mass Cloud Resource Deletions Time Series Anomaly": [
    ["TRIAGE", [
      "Identify the Azure subscription(s), resource group(s), and account(s) involved",
      "Determine the volume and type of resources deleted — VMs, storage, databases, networking?",
      "Establish the timeframe and whether deletions are ongoing",
      "Check whether this is a known maintenance activity or completely unexpected",
      "Identify whether deletion was performed by a human user, service principal, or automation",
    ]],
    ["INVESTIGATION", [
      "Pull Azure Activity Log entries for all delete operations — note Caller, CallerIpAddress, OperationName, ResourceId",
      "Review the calling account's sign-in history: unusual location, IP, device, or time",
      "Check whether the account is a service principal — review permissions and recent credential changes",
      "Check whether resource locks were bypassed or removed before deletion",
      "Review whether backups, snapshots, or soft-delete protections exist for deleted resources",
      "Search for other anomalous Azure management operations from the same account",
      "Identify business impact: which services or workloads have been taken offline?",
    ]],
    ["IOC ENRICHMENT", [
      "Check the calling IP against AbuseIPDB and Azure known safe IP ranges",
      "If a service principal: check for recent credential rotation or new client secrets",
      "Search SIEM for other bulk management operations from the same Caller in the past 7 days",
    ]],
    ["CONTAINMENT", [
      "If malicious: disable the calling account or service principal immediately",
      "Revoke all active sessions and OAuth tokens for the account",
      "Apply Azure subscription-level resource locks to prevent further deletions",
      "Initiate recovery of deleted resources via Recovery Vault, soft-delete, or snapshots",
      "Notify resource owners and business stakeholders of the impact",
    ]],
    ["ESCALATION CHECK", [
      "Backups or DR resources deleted? → Escalate to L2 / CISO — potential ransomware",
      "Production services offline? → Escalate to L2 / CISO and initiate BCP",
      "Service principal or admin account confirmed compromised? → Escalate to L2",
      "Multiple subscriptions affected? → Escalate to L2 / CISO immediately",
    ]],
    ["CLOSURE", [
      "Confirm the calling account/service principal is secured",
      "Document all deleted resources, business impact, and recovery status",
      "Confirm resource locks are in place on critical subscriptions",
      "Complete root cause analysis: how did the actor gain delete permissions?",
      "Recommend Azure RBAC review and principle of least privilege audit",
    ]],
  ],
  "Anomalous Remote Access Tool Usage": [
    ["TRIAGE", [
      "Identify the host, user, and specific remote access tool flagged (AnyDesk, TeamViewer, ngrok, RustDesk, ScreenConnect, Cobalt Strike)",
      "Determine whether this tool is sanctioned and used legitimately",
      "Check whether the tool was pre-installed, freshly dropped, or installed by a process",
      "Identify the parent process that installed or launched the tool",
      "Confirm whether an outbound connection was established and to which IP/domain",
    ]],
    ["INVESTIGATION", [
      "Pull process creation events — note full path, hash, parent process, and command-line",
      "Review the tool's network connections: destination IP, port, and protocol",
      "Check installation directory — legitimate tools use Program Files; malicious often use temp/AppData",
      "Submit the file hash to VirusTotal",
      "Check the destination IP/domain against AbuseIPDB and threat intel",
      "Review the host's full process timeline for signs of prior compromise",
      "Check for persistence: startup, scheduled tasks, or services",
      "Review whether the session resulted in interactive activity: file access, command execution",
      "Search SIEM for the same tool binary hash or C2 IP/domain across other endpoints",
      "If ngrok or similar: identify what service was being exposed externally",
    ]],
    ["CONTAINMENT", [
      "Isolate the host if an active RAT session is confirmed or suspected",
      "Terminate the RAT process if still running",
      "Block the destination IP and domain at firewall and proxy",
      "Remove persistence mechanisms",
      "Disable the affected user account and revoke active sessions",
      "Quarantine and hash-block the RAT binary",
    ]],
    ["ESCALATION CHECK", [
      "Confirmed active C2 session? → Escalate to L2 / IR immediately",
      "Tool installed by malware dropper or phishing? → Escalate to L2",
      "Multiple hosts running the same RAT? → Escalate to L2 / IR",
      "ngrok or tunnel exposing internal services? → Escalate to L2 immediately",
    ]],
    ["CLOSURE", [
      "Confirm host is isolated, tool removed, and persistence cleared",
      "Confirm all C2 infrastructure is blocked at network level",
      "Document binary hash, C2 IP/domain, persistence mechanism, and process chain",
      "Recommend EDR policy to block unsanctioned remote access tools",
    ]],
  ],
  "Time Series Anomaly for Data Size Transferred to Public Internet": [
    ["TRIAGE", [
      "Identify the source host, user, and destination responsible for the anomalous transfer",
      "Determine the volume and how it compares to baseline — 2x, 10x, or 100x normal?",
      "Identify the protocol and application: HTTPS, FTP, cloud sync client?",
      "Check whether this was during or outside business hours",
      "Check whether this matches any known backup, update, or legitimate business activity",
    ]],
    ["INVESTIGATION", [
      "Pull firewall/proxy logs for source host and destination — bytes transferred, duration, protocol",
      "Identify the process responsible for the outbound traffic on the host",
      "Review the destination: personal cloud storage, file sharing site, or unknown IP?",
      "Check DLP alerts for the same timeframe on the same host or user",
      "Review host process timeline: was a staging or archiving tool used (7zip, WinRAR)?",
      "Check whether large files were recently created on the host before the transfer",
      "Review the user's recent access to sensitive file shares or databases",
      "Search SIEM for the same destination IP/domain from other hosts",
    ]],
    ["IOC ENRICHMENT", [
      "Check the destination IP against AbuseIPDB and threat intel",
      "Check the destination domain against VirusTotal and WHOIS for age/registration",
      "Search SIEM for other anomalous outbound transfers from the same host or user",
    ]],
    ["CONTAINMENT", [
      "Block the destination IP and domain at proxy/firewall if malicious or unauthorised",
      "Isolate the host if active exfiltration is ongoing or malware is confirmed",
      "Disable the user account if compromise or insider threat is suspected",
      "Preserve all relevant logs before any rotation occurs",
    ]],
    ["ESCALATION CHECK", [
      "Sensitive or regulated data confirmed in transfer? → Escalate to L2 / DPO — potential breach",
      "Deliberate staging and exfiltration by insider? → Escalate to L2 / HR / Legal",
      "Malware confirmed responsible? → Escalate to L2 / IR",
      "Multiple hosts transferring to same external destination? → Escalate to L2 / IR",
    ]],
    ["CLOSURE", [
      "Confirm exfiltration has stopped and destination is blocked",
      "Document volume, destination, responsible process, and data classification",
      "Assess whether formal breach notification is required under GDPR",
      "Recommend DLP policy review to detect and block this type of transfer earlier",
    ]],
  ],
  "Email Messages Removed After Delivery": [
    ["TRIAGE", [
      "Identify who or what removed the emails: user self-deletion, admin purge, ZAP, or inbox rule",
      "Identify the emails removed: sender, subject, attachment, number of mailboxes affected",
      "Determine the timeframe between delivery and removal",
      "If ZAP: confirm which threat type triggered the recall (malware, phish, spam)",
      "If inbox rule or user action: treat as suspicious and investigate further",
    ]],
    ["INVESTIGATION", [
      "Pull Unified Audit Log for RemoveMalware, HardDelete, SoftDelete, or MoveToDeletedItems operations",
      "If ZAP triggered: review the ZAP report in Defender portal for the full threat verdict",
      "If an inbox rule removed the emails: pull rule details — name, conditions, action, and when created",
      "Identify all mailboxes from which the email was removed",
      "Check whether any users interacted with the email before removal: links clicked, attachments opened",
      "For any users who interacted: review their endpoint activity in MDE",
      "Review sender reputation, SPF/DKIM/DMARC, and sending IP",
      "Check Threat Explorer for the full campaign scope",
      "If inbox rule deletion: check for other suspicious inbox rules (forwarding, deletion by keyword)",
    ]],
    ["IOC ENRICHMENT", [
      "Submit URLs from the removed email to VirusTotal / URLScan.io",
      "Submit attachment hashes to VirusTotal",
      "Check sender IP and domain against AbuseIPDB",
      "Search SIEM for the same sender, subject, or attachment hash across other users",
    ]],
    ["CONTAINMENT", [
      "Purge any remaining copies of the email via MDO Content Search",
      "Block sender address, sending IP, and malicious URLs or hashes at the email gateway",
      "If users clicked links or opened attachments: isolate affected endpoints",
      "If inbox rule is responsible: delete the rule and check for account compromise",
      "If account compromise suspected: reset password, revoke sessions, re-enrol MFA",
    ]],
    ["ESCALATION CHECK", [
      "Users confirmed to have clicked links or opened malicious attachments? → Escalate to L2 / IR",
      "Inbox rule created by attacker to auto-delete emails? → Escalate to L2 — active compromise",
      "Large-scale campaign targeting multiple users? → Escalate to L2",
      "Malware delivered and executed before ZAP removed the email? → Escalate to L2 / IR",
    ]],
    ["CLOSURE", [
      "Confirm all copies of the email are removed across the tenant",
      "Confirm all IOCs are blocked at the email gateway",
      "Confirm affected endpoints are remediated if any interaction occurred",
      "Document campaign scope, threat verdict, removal method, and user interaction",
      "Review Defender for Office 365 policies to ensure ZAP is enabled",
    ]],
  ],
  "TI Map Domain Entity to DeviceNetworkEvents": [
    ["TRIAGE", [
      "Identify the device, user, and process responsible for the DNS resolution or connection to the TI-matched domain",
      "Note the threat intelligence classification: C2, malware distribution, phishing, botnet, cryptomining",
      "Determine whether the connection was blocked or allowed through",
      "Establish when the connection occurred and whether it is ongoing",
      "Check if the device is a server, workstation, or shared system",
    ]],
    ["INVESTIGATION", [
      "Pull DeviceNetworkEvents from MDE Advanced Hunting — note RemoteUrl, RemoteIP, RemotePort, InitiatingProcessFileName",
      "Identify the initiating process: what application resolved or connected to the domain?",
      "Check whether the domain resolved successfully and whether a full session was established",
      "Review the initiating process's parent process chain",
      "Check the process binary hash against VirusTotal",
      "Search DeviceNetworkEvents across the estate for other devices contacting the same domain",
      "Check for file downloads from the domain correlated with the same process/timeframe",
      "Check DNS query logs for historical lookups to the domain from the device",
      "Assess whether this is a beaconing pattern: regular intervals, consistent byte sizes",
    ]],
    ["IOC ENRICHMENT", [
      "Check the domain and resolved IP against VirusTotal, AbuseIPDB, and URLScan.io",
      "Check WHOIS for domain registration age and registrar",
      "Check passive DNS records: does this domain resolve to known malicious infrastructure?",
      "Search threat intel for the domain for actor attribution",
      "Check Shodan for the resolved IP",
    ]],
    ["CONTAINMENT", [
      "Block the domain and resolved IP at DNS, proxy, and firewall immediately",
      "If C2 communication confirmed: isolate the device from the network",
      "Terminate the malicious process if still running",
      "Disable the user account if credential compromise is suspected",
      "Block the process binary hash at MDE if confirmed malicious",
    ]],
    ["ESCALATION CHECK", [
      "Confirmed C2 beacon to known threat actor infrastructure? → Escalate to L2 / IR immediately",
      "File download from domain confirmed? → Escalate to L2",
      "Multiple devices beaconing to same domain? → Escalate to L2 / IR",
      "Domain linked to known ransomware or APT actor? → Escalate to L2 / CISO immediately",
    ]],
    ["CLOSURE", [
      "Confirm domain and IP are blocked across all enforcement points",
      "Confirm device is remediated or reimaged if compromise was confirmed",
      "Document initiating process, domain, resolved IP, connection details, and TI classification",
      "Update the SIEM TI feed with the new IOC if not already present",
    ]],
  ],
  "Rare Subscription-Level Operations in Azure": [
    ["TRIAGE", [
      "Identify the specific Azure operation flagged: policy assignment, role assignment, diagnostic setting, key vault access policy?",
      "Identify the caller account or service principal and confirm whether this is expected",
      "Check whether the operation was from a known trusted IP and location",
      "Determine whether a change request exists that authorises this activity",
      "Note the subscription and resource scope — tenant-wide changes are higher severity",
    ]],
    ["INVESTIGATION", [
      "Pull the full Azure Activity Log entry: Caller, CallerIpAddress, OperationName, ResourceId, SubscriptionId",
      "Review the caller account's sign-in history: unusual IP, location, device, or time",
      "Check whether MFA was satisfied for the session",
      "Review all Activity Log entries for the same caller in the past 7 days",
      "Identify the blast radius: what does this operation change, expose, or enable?",
      "If a role assignment: who was granted what role on which scope?",
      "If a diagnostic setting was modified: has security logging been impaired?",
      "If Key Vault access policy changed: what secrets/keys may now be accessible?",
      "If policy assignment changed: have security controls been weakened?",
    ]],
    ["IOC ENRICHMENT", [
      "Check the caller IP against AbuseIPDB — residential IP, VPN, Tor, or known attacker?",
      "If a service principal: review its permissions and recent credential changes",
      "Check Azure AD audit log for the caller: MFA bypass, conditional access failure, risky sign-in?",
    ]],
    ["CONTAINMENT", [
      "If unauthorised: disable the calling account or service principal immediately",
      "Revoke all active sessions and refresh tokens",
      "Reverse the operation where possible: remove role, restore policy, revert diagnostic setting",
      "Apply resource locks on critical subscriptions",
      "If Key Vault access was modified: rotate all secrets and keys that may have been accessed",
    ]],
    ["ESCALATION CHECK", [
      "Diagnostic settings deleted — security logging impaired? → Escalate to L2 immediately",
      "Owner or Contributor role granted at subscription scope? → Escalate to L2 / CISO",
      "Key Vault access policy changed — secrets may be exposed? → Escalate to L2",
      "Security policies weakened? → Escalate to L2 / CISO",
      "Multiple anomalous operations in same session? → Escalate to L2",
    ]],
    ["CLOSURE", [
      "Confirm the operation has been reversed and account secured",
      "Document the operation type, resource scope, caller IP, and timeline",
      "Confirm Azure security logging is fully restored if impaired",
      "Complete an RBAC audit on the affected subscription",
      "Recommend implementing Azure PIM for just-in-time privileged access",
    ]],
  ],
  "Suspicious DNS Tunnel Behaviour Blocked": [
    ["TRIAGE", [
      "Identify the device, user, and process that generated the flagged DNS traffic",
      "Confirm the traffic was blocked and at which enforcement point",
      "Note the destination domain flagged for DNS tunnelling behaviour",
      "Determine whether this is a known tunnelling tool (iodine, dnscat2, DNSExfiltrator) or anomalous patterns",
      "Assess whether any data was successfully exfiltrated before blocking",
    ]],
    ["INVESTIGATION", [
      "Pull DNS query logs — look for: unusually long subdomain labels, high query frequency, TXT/NULL/MX queries with encoded data, base32/base64 encoded subdomains",
      "Identify the initiating process responsible for the DNS queries",
      "Submit the process binary hash to VirusTotal",
      "Review the process parent chain — spawned by malicious document, script, or lateral movement?",
      "Check the device's full process and network event timeline",
      "Assess query volume and pattern: is there a beaconing interval suggesting C2 over DNS?",
      "Check whether the same domain was queried historically before the block",
      "Search across all devices in SIEM for queries to the same domain",
    ]],
    ["IOC ENRICHMENT", [
      "Check the destination domain against VirusTotal, AbuseIPDB, and passive DNS",
      "Check WHOIS for domain registration — newly registered or bulletproof hosting?",
      "Identify the DNS server used — is the device using a custom external resolver to bypass filtering?",
      "Search threat intel for the domain — known threat actor or malware family?",
    ]],
    ["CONTAINMENT", [
      "Confirm the domain is blocked at all DNS enforcement points across the estate",
      "Isolate the affected device — DNS tunnelling with active C2 is a critical indicator",
      "Terminate the tunnelling process if still running",
      "Remove any persistence mechanisms identified",
      "Disable the user account if credential compromise is suspected",
      "Block the tunnelling tool binary hash at MDE",
    ]],
    ["ESCALATION CHECK", [
      "Data exfiltration via DNS confirmed or suspected? → Escalate to L2 / IR and DPO immediately",
      "Active C2 session established via DNS tunnel? → Escalate to L2 / IR immediately",
      "Known malware family identified as the tunnelling agent? → Escalate to L2 / IR",
      "Multiple devices using DNS tunnelling to same domain? → Escalate to L2 / IR",
    ]],
    ["CLOSURE", [
      "Confirm device is isolated and fully remediated or reimaged",
      "Confirm domain is blocked at all DNS enforcement points",
      "Document the tunnelling tool, domain, query patterns, and process chain",
      "Assess whether any data was successfully exfiltrated and initiate breach assessment if required",
      "Recommend DNS logging improvements (Sysmon DNS, PDNS)",
      "Recommend blocking custom DNS resolvers to prevent bypass of DNS filtering",
    ]],
  ],
};

export const INCIDENT_TYPES = Object.keys(TRAINING_CHECKLISTS);
